sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 14777
  alioss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    accessKeyId: LTAI5tMA9UmFkFgP5UJCCWc4
    accessKeySecret: FfRQ6ILXCfF3DGKQBNu1RHWOPrAt8Y
    bucketName: study-web-001
  redis:
    host: localhost
    port: 6379
    password: 14777
    database: 10